Fixed crash heh
Polyfrost/Chatting pull request #15
Opened 2023-01-13 01:27 UTC by sinender

Just erm, fixing the thing I created, but didn't test well enough :D

2023-01-13 01:41 UTC, sinender commented
I promise things work this time! I have tested this with multiple clients and other people!

2023-01-15 23:49 UTC, Wyvest requested changes

2023-01-15 23:49 UTC, Wyvest commented on src/main/java/cc/woverflow/chatting/mixin/GuiNewChatMixin.java
> +        if (updateCounter != -1) {
wait so what is updateCounter i honestly still don't get how chat works lol

2023-01-15 23:49 UTC, Wyvest commented on src/main/kotlin/cc/woverflow/chatting/chat/ChatTab.kt
> +        if (messages != null) {
can you use messages?.let instead of this

2023-01-15 23:49 UTC, Wyvest commented on src/main/kotlin/cc/woverflow/chatting/chat/ChatTabs.kt
> +    var previousTab: ChatTab? = null
can you update this to the new changes introduced in recent commits

2024-02-27 00:29 UTC, closed without merging